GetSpecificInfoTask:
  description: |
    Instructions:
    1. Analyze the document thoroughly using contextual clues and detailed instructions.
    2. Identify all required items and locate the relevant sections where data is presented.
    3. Extract each specified field (e.g., dates, monetary values, names) ensuring they strictly follow the formatting rules.
    4. Cross-reference and validate related fields to guarantee consistency and logical accuracy.
    5. Assemble the extracted data into a JSON object that adheres exactly to the provided schema.

    {detailed_instructions}

    Input Data for reference:

    Document Content: 
    
    {document_content}

  expected_output: |
    A JSON object that strictly adheres to the schema provided in the detailed instructions, including all specified fields (even if empty), with proper formatting and no additional text